---
- name: Delete mariadb
  yum:
    name: mariadb-libs
    state: removed

- name: Install mysql repo
  shell:
    cmd: |
      wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
      yum localinstall -y mysql80-community-release-el7-3.noarch.rpm

- name: Install mysql
  yum:
    name: mysql-community-server
  with_items:
    - mysql-community-devel
    - MySQL-python

- name: Copy my.cnf
  template:
    src: my.cnf
    dest: /etc/my.cnf
    mode: 0644

- name: Restart mysql
  service:
    name: mysqld
    state: restarted

- name: Enable mysql start on boot
  service:
    name: mysqld
    enabled: yes

- block:
  - name: Install pip
    shell:
      cmd: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py

  - name: Install PyMySQL module for python
    pip:
      name: PyMySQL

  - name: Get mysql root tmp password
    shell: "grep -oP '(?<=root@localhost: ).*' /var/log/mysqld.log"
    register: get_mysql_tmp_pass

  - name: Set mysql root user
    command: |
      mysql --user root \
            --password={{ get_mysql_tmp_pass.stdout }} 
            --connect-expired-password 
            --execute="ALTER USER 'root'@'localhost' \
                       IDENTIFIED BY '{{ mysql_root_password }}';"