---
- name: Install mysql
  shell:
    cmd: |
      wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
      yum localinstall mysql80-community-release-el7-3.noarch.rpm
      yum install mysql-community-server

- name: Start mysql, if not started
  service:
    name: mysqld
    state: started

- name: Enable mysql start on boot
  service:
    name: mysqld
    enabled: yes

- block:
  - name: Install pip
    shell:
      cmd: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py

  - name: Install PyMySQL module for python
    pip:
      name: PyMySQL

  - name: Set mysql root user
    mysql_user:
      login_user: root
      login_password: "{{ get_mysql_tmp_pass.stdout }}"
      name: root
      host: localhost
      password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      state: present