---
- name: Install mysql
  shell:
    cmd: |
      wget https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm
      yum localinstall -y mysql80-community-release-el7-3.noarch.rpm
      yum install -y mysql-community-server

- name: Start mysql, if not started
  service:
    name: mysqld
    state: started

- name: Enable mysql start on boot
  service:
    name: mysqld
    enabled: yes

- block:
  - name: Install pip
    shell:
      cmd: |
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py

  - name: Install PyMySQL module for python
    pip:
      name: PyMySQL

  - shell: "grep -oP '(?<=root@localhost: ).*' /var/log/mysqld.log"
    register: get_mysql_tmp_pass

  - set_fact:
      mysql_tmp_pass: "{{ get_mysql_tmp_pass.stdout }}"

  - name: Set mysql root user
    mysql_user:
      login_user: "root"
      login_password: "{{ mysql_tmp_pass }}"
      name: root
      password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      state: present