---
- name: Download mysql repo
  get_url:
    url: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
    dest: /tmp/mysql57-community-release-el7-11.noarch.rpm

- name: Prepare repo for installation
  yum:
    name: /tmp/mysql57-community-release-el7-11.noarch.rpm
    state: present

- name: Install mysql
  yum:
    name: mysql-community-server
    state: present

# - name: Install mysql
#   yum:
#     name: https://dev.mysql.com/get/mysql57-community-release-el7-11.noarch.rpm
#     state: present

- name: Start mysql, if not started
  service:
    name: mysqld
    state: started

- name: Enable mysql start on boot
  service:
    name: mysqld
    enabled: yes
